#! /bin/sh
##########################################################
#  |  __ \ \    / /  __ \| |        /\   |  _ \ / ____|  #
#  | |  | \ \  / /| |__) | |       /  \  | |_) | (___    #
#  | |  | |\ \/ / |  _  /| |      / /\ \ |  _ < \___ \   #
#  | |__| | \  /  | | \ \| |____ / ____ \| |_) |____) |  #
#  |_____/   \/   |_|  \_\______/_/    \_\____/|_____/   #
##########################################################
# CONFIGURATON - bspwmrc                                 #               
##########################################################
# SUMMARY      - init file for bspwm                     #      
##########################################################
# VERSION      - 1.0.0                                   # 
##########################################################
# DATE         - 03/16/22                                #      
##########################################################
# GITHUB       -                                         # 
##########################################################

#Start hot key daemon.
pgrep -x sxhkd > /dev/null || sxhkd &

##########################################################
# Monitors/Workspaces                    left to right   # 
##########################################################
bspc monitor DVI-D-0 -d       1   2   3     4 
bspc monitor HDMI-A-0 -d      one two three four 
bspc monitor DisplayPort-1 -d I   II  III   IV 


##########################################################
# bspwm configuration options                            # 
##########################################################
bspc config border_width         5
bspc config window_gap          10
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color \#3daee9
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_modifier mod4 
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner


##########################################################
# Rules for specific applications                        # 
##########################################################
bspc rule -a ulauncher state=floating follow=off
bspc rule -a ulauncher-toggle state=floating follow=off
bspc rule -a expandedViewDriver.py state=floating follow=off


##########################################################
# Autostart                                              # 
##########################################################
ulauncher --hide-window &
autorandr i3wm &
picom &
sh -c 'sleep 5; exec nitrogen --restore &'
~/.config/polybar/launch.sh 





